version: 2.1
orbs:
  maven: circleci/maven@1.1

executors:
  jdk11:
    docker:
      - image: 'cimg/openjdk:11.0'

jobs:
  build:
    executor: jdk11
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: MAVEN_OPTS=-Xmx3200m mvn verify
      - maven/process_test_results

workflows:
  build:
    jobs:
      - build
